<?php

namespace App\Providers;

use App\Actions\Fortify\CreateAdmin;
use App\Actions\Fortify\ResetAdminPassword;
use App\Http\Responses\Auth\AdminPasswordResetResponse;
use App\Http\Responses\Auth\AdminRegisterResponse;
use App\Models\Admin;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Contracts\Auth\StatefulGuard;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Password;
use Inertia\Inertia;
use Laravel\Fortify\Contracts\PasswordResetResponse;
use Laravel\Fortify\Contracts\RegisterResponse;
use Laravel\Fortify\Fortify;

class FortifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        Fortify::ignoreRoutes();

        $this->app->singleton(RegisterResponse::class, AdminRegisterResponse::class);
        $this->app->singleton(PasswordResetResponse::class, AdminPasswordResetResponse::class);
        $this->app->bind(StatefulGuard::class, fn (): StatefulGuard => match (request()->getHost()) {
            config('domains.admin') => Auth::guard('admin'),
            config('domains.member') => Auth::guard('member'),
            default => $this->app->runningInConsole()
                ? Auth::guard('admin')
                : throw new \LogicException('No authentication guard is configured for this host.'),
        });
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->configureActions();
        $this->configureViews();
        $this->configureRateLimiting();
        $this->configureNotificationUrls();
    }

    /**
     * Configure Fortify actions.
     */
    private function configureActions(): void
    {
        Fortify::resetUserPasswordsUsing(ResetAdminPassword::class);
        Fortify::createUsersUsing(CreateAdmin::class);
    }

    /**
     * Configure Fortify views.
     */
    private function configureViews(): void
    {
        Fortify::resetPasswordView(fn (Request $request) => Inertia::render('auth/ResetPassword', [
            'email' => $request->email,
            'token' => $request->route('token'),
            'passwordRules' => Password::defaults()->toPasswordRulesString(),
        ]));

        Fortify::requestPasswordResetLinkView(fn (Request $request) => Inertia::render('auth/ForgotPassword', [
            'status' => $request->session()->get('status'),
        ]));

        Fortify::verifyEmailView(fn (Request $request) => Inertia::render('auth/VerifyEmail', [
            'status' => $request->session()->get('status'),
        ]));

        Fortify::registerView(fn () => Inertia::render('auth/Register', [
            'passwordRules' => Password::defaults()->toPasswordRulesString(),
        ]));

        Fortify::confirmPasswordView(fn () => Inertia::render('auth/ConfirmPassword'));
    }

    /**
     * Configure rate limiting.
     */
    private function configureRateLimiting(): void
    {
        RateLimiter::for('admin-login', function (Request $request) {
            $throttleKey = Str::transliterate(Str::lower($request->string(Fortify::username())).'|'.$request->ip());

            return Limit::perMinute(5)->by('admin|'.$throttleKey);
        });

        RateLimiter::for('member-login', function (Request $request) {
            $throttleKey = Str::transliterate(Str::lower($request->input(Fortify::username())).'|'.$request->ip());

            return Limit::perMinute(5)->by('member|'.$throttleKey);
        });
    }

    /**
     * Configure URLs generated by admin authentication notifications.
     */
    private function configureNotificationUrls(): void
    {
        ResetPassword::createUrlUsing(fn (Admin $admin, string $token): string => route('admin.password.reset', [
            'token' => $token,
            'email' => $admin->getEmailForPasswordReset(),
        ]));

        VerifyEmail::createUrlUsing(fn (Admin $admin): string => URL::temporarySignedRoute(
            'admin.verification.verify',
            now()->addMinutes((int) config('auth.verification.expire', 60)),
            [
                'id' => $admin->getKey(),
                'hash' => sha1($admin->getEmailForVerification()),
            ],
        ));
    }
}
